Pre develop
frontend-park-mail-ru/2021_2_SnakeAlive pull request #6
Opened 2021-09-22 20:33 UTC by znjuko

2021-09-25 19:15 UTC, alexey-ershkov requested changes

2021-09-25 19:15 UTC, alexey-ershkov commented on src/index.css
> +:root {
Лайк за css переменные

2021-09-25 19:15 UTC, alexey-ershkov commented on src/main.js
> +	// const btnSignup = new Button('Зарегистрироваться', 'startBtn', 'signup', header);
???

2021-09-25 19:15 UTC, alexey-ershkov commented on src/main.js
> +import { Button } from './components/bundle.js';
Опять же main - тоже называют index

2021-09-25 19:15 UTC, alexey-ershkov commented on src/start.css
> +.err > span {
Лучше не использовать такие селекторы, а накинуть больше классов. вложенность очень часто меняется и полагаться на нее не стоит

2021-09-25 19:15 UTC, alexey-ershkov commented on src/validation/common.js
> +const checkEmpty = (value = '', name = '') => {
checkIsEmpty

2021-09-25 19:15 UTC, alexey-ershkov commented on src/validation/common.js
> +	const re = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
Откуда такая страшная регулярка? Кажется все можно сделать проще

2021-09-25 19:15 UTC, alexey-ershkov commented on src/validation/common.js
> +	if (!re.test(String(value).toLowerCase())) {
А смысл делать toLowerCase, если в регулярке есть заглавные буквы? Напишите лучше свою простую регулярку, чем копипастить из интернета

2021-09-25 19:15 UTC, alexey-ershkov commented on src/index.html
> +			<header class="block" id="header">
Здесь ничего этого быть не должно!!! Это не SPA Только div с классом root и все !!!
![Ментор расстроен](https://user-images.githubusercontent.com/56301773/134783648-5e3ee39d-32f6-4e1d-b1cb-b5b3dcde92ed.jpeg)

2021-09-26 23:08 UTC, znjuko commented on src/validation/common.js
> +const checkEmpty = (value = '', name = '') => {
+

2021-09-26 23:09 UTC, znjuko commented on src/components/bundle.js
> +export { Form, FormRequire, Button };
+

2021-09-26 23:09 UTC, znjuko commented on package.json
> +    "ch-pretty": "prettier --check .",
+

2021-09-26 23:09 UTC, znjuko commented on .prettierrc.json
> +}
+

2021-09-26 23:09 UTC, znjuko commented on .gitignore
> +package-lock.json
+

2021-09-26 23:11 UTC, znjuko commented on src/validation/common.js
> +	const re = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
+

2021-09-26 23:11 UTC, znjuko commented on src/validation/common.js
> +	if (!re.test(String(value).toLowerCase())) {
+

2021-09-26 23:30 UTC, znjuko commented on src/index.html
> +			<header class="block" id="header">
![Снимок экрана 2021-09-27 в 02 30 25](https://user-images.githubusercontent.com/48394965/134827928-c179d625-b689-41f3-9573-dc276922b474.png)

2021-09-26 23:32 UTC, znjuko commented on src/validation/common.js
> +	if (!re.test(String(value).toLowerCase())) {
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134827984-ac32ce5d-ab58-4d22-b470-25ff2aa04bde.png)

2021-09-26 23:32 UTC, znjuko commented on src/validation/common.js
> +	const re = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134827984-ac32ce5d-ab58-4d22-b470-25ff2aa04bde.png)

2021-09-26 23:32 UTC, znjuko commented on src/validation/common.js
> +const checkEmpty = (value = '', name = '') => {
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134827984-ac32ce5d-ab58-4d22-b470-25ff2aa04bde.png)

2021-09-26 23:32 UTC, znjuko commented on src/components/bundle.js
> +export { Form, FormRequire, Button };
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134827984-ac32ce5d-ab58-4d22-b470-25ff2aa04bde.png)

2021-09-26 23:33 UTC, znjuko commented on package.json
> +    "ch-pretty": "prettier --check .",
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134827984-ac32ce5d-ab58-4d22-b470-25ff2aa04bde.png)

2021-09-26 23:33 UTC, znjuko commented on .prettierrc.json
> +}
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134827984-ac32ce5d-ab58-4d22-b470-25ff2aa04bde.png)

2021-09-26 23:33 UTC, znjuko commented on .gitignore
> +package-lock.json
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134827984-ac32ce5d-ab58-4d22-b470-25ff2aa04bde.png)

2021-09-26 23:34 UTC, znjuko commented on package.json
> +    "absolute-imports": "^1.0.1",
![изолятор мем для дебилов](https://user-images.githubusercontent.com/48394965/134828032-1560b573-eefb-4f77-b09b-433701632262.jpg)

2021-09-26 23:43 UTC, znjuko commented on package.json
> +    "absolute-imports": "^1.0.1",
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134828306-b860052e-d91d-42af-8228-dc8171a536f0.png)

2021-09-26 23:59 UTC, znjuko commented on src/start.css
> +.err > span {
![wip](https://user-images.githubusercontent.com/48394965/134828774-776c92d0-be27-4606-9938-f698873f6bd1.png)

2021-09-27 16:49 UTC, znjuko commented on src/index.html
> +			<header class="block" id="header">
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134951742-ee11bbc4-4c05-4553-8a49-96f6db741042.png)

2021-09-27 16:50 UTC, znjuko commented on src/start.css
> +.err > span {
![Снимок экрана 2021-09-27 в 02 32 25](https://user-images.githubusercontent.com/48394965/134951898-e5f6cd09-6a0f-4d46-8061-ed8983dfe8a7.png)

2021-09-28 21:36 UTC, alexey-ershkov requested changes

2021-09-28 21:36 UTC, alexey-ershkov commented on package.json
> +    "prettier": "^2.4.1"
тоже в devDeps

2021-09-28 21:36 UTC, alexey-ershkov commented on src/adapters/adapt_get_cards.js
> +			imgs: card.photos.map((photo, photoIndex) => ({
photoIndex не используете

2021-09-28 21:36 UTC, alexey-ershkov commented on src/components/button.js
> +	 * Эта восхитительный метод проверяет, передали в него тот же объект или нет
"Эта восхитетительный"?

2021-09-28 21:36 UTC, alexey-ershkov commented on src/components/button.js
> +	 * @param {Object} DOMelement [= null] Существующий html-элемент.
`@param {Object|null}`

2021-09-28 21:36 UTC, alexey-ershkov commented on src/components/form.js
> +		config.inputs.forEach(i => {
уберите и отвыкните от индексов i и j - пишите полноценно - что за итерируемый объект. Здесь и далее

![image](https://user-images.githubusercontent.com/56301773/135167539-a943c5e4-1687-455b-8814-56794a68e420.png)

2021-09-28 21:36 UTC, alexey-ershkov commented on src/components/form.js
> +				this.#inputs.forEach(i => i.clearErrors());
Не исправили

2021-09-28 21:36 UTC, alexey-ershkov commented on src/constants/defaults.js
> +const nicaraguaFormName = 'Никарагуа';
Form - так себе название  - хотя russiaTitleName

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/country_sights.js
> +	btnExit.addClickListener(() => showCountrySights());
Зачем вызывать самого себя по клику? рекурсия же - не?

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/country_sights.js
> +		it = (it + 1) % map.length;
it - так себе название переменной

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/footer.js
> +	return template({
Кажется template лишняя переменная - можно сразу вызывать Handlebars.templates.footer

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/header.js
> +const showLoginForm = (callbacks = []) => {
Логика с созданием формы не должна относиться к хедеру. Относится к логину и регистрации - каждый в отдельный файл.

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/header.js
> +const setUserHeader = (user, callbacks = []) => {
Тоже по отдельным файлам

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/header.js
> +function chooseHeaderType() {
Здесь ток это должно остаться и логика ниже

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/inner.js
> +	const template = Handlebars.templates.inner;
опять же template можно опустить

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/login.js
> + * @promise fPromise
fPromise?

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/register.js
> +			const password = registerInputs.pswd;
`const {pswd as password} = registerInputs;`

также можно сократить - `const {email, pswd as password, name, surname} = registerInputs;`

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/set_columns_amount_cards.js
> +	if (width < 900) {
Это должно быть в css - по сути это как раз на grid-ах или flex-ах надо делать

2021-09-28 21:36 UTC, alexey-ershkov commented on src/forms/set_columns_amount_cards.js
> +		grid.classList.remove('card__grid__2');
Название классов изменить

2021-09-28 21:36 UTC, alexey-ershkov commented on src/index.css
> +body,
Разбейте css на разные файлы - можно по компонентам. CSS поддерживает импорты внутри себя - не пишите все в одном файле. Прошу

2021-09-28 21:36 UTC, alexey-ershkov commented on src/index.html
> +		<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.7/handlebars.min.js"></script>
Зачем вам рантайм и не рантайм handlebars одновременно?

2021-09-28 21:36 UTC, alexey-ershkov commented on src/templates/country_sights.handlebars
> +</div>
Поменять название классов с цифрами и сделать перенос в конце строки

2021-09-28 21:36 UTC, alexey-ershkov commented on src/templates/header.handlebars
> +</div>
Перенос в конце

2021-09-28 21:36 UTC, alexey-ershkov commented on src/templates/footer.handlebars
> +</div>
Перенос в конце

2021-09-28 21:36 UTC, alexey-ershkov commented on src/templates/header_user.handlebars
> +<p> {{name}} {{surname}} </p>
Перенос в конце

2021-09-28 21:36 UTC, alexey-ershkov commented on src/templates/inner.handlebars
> +<div id="popup-place"></div>
перенос в конце

2021-09-28 21:36 UTC, alexey-ershkov commented on src/templates/header_user.handlebars
> +<p> {{name}} {{surname}} </p>
Кажется это можно объединить с шаблоном хедера по if-у

2021-09-28 21:36 UTC, alexey-ershkov commented on src/validation/login.js
> +		.then(() => checkIsEmpty(input.pswd, 'pswd'))
кажется проще переименовать на password, для единства названий

2021-09-29 08:40 UTC, alexey-ershkov requested changes

2021-09-29 08:40 UTC, alexey-ershkov commented on src/constants/endpoints.js
> +// 194.58.104.204
Эммм - верните обратно

2021-09-29 09:46 UTC, merged